package org.team1277.frc.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths

/**
 * Sets up the FRC SDK properties located in
 * {@code ~/.sunspotfrc.properties}
 */
class ConfigureSDKProperties extends DefaultTask
{
	SDK sdk

	@Input
	String remoteAddress

	@Input
	public String getSDKLocation()
	{
		return getSdk().root.toAbsolutePath().toString()
	}

	@OutputFile
	public File getSDKPropertiesFile()
	{
		return getSdk().getPropertiesFile().toFile()
	}

	@TaskAction
	public void writeProperties()
	{
		Properties props = new Properties()
		props.setProperty('sunspot.home', getSDKLocation())
		props.setProperty('remoteaddress', getRemoteAddress())

		Path propertiesLocation = getSdk().getPropertiesFile()

		logger.debug("Writing SDK properties to {}: {}", propertiesLocation, props)

		propertiesLocation.withOutputStream { o ->
			props.store(o, "Automatically generated by gradle-frc-plugin")
		}
	}
}
